# Build pipeline

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BuildVersion: 0
  
steps:
- task: PowerShell@2
  displayName: 'Set Build Version'
  inputs:
    targetType: 'inline'
    script: |
      $timestamp = git log -1 --pretty="format:%ct"
      Write-Host "Build Version: $timestamp" 
      Write-Host "##vso[task.setvariable variable=BuildVersion]$($timestamp)"

#- task: PowerShell@2
#  displayName: 'Version Info'
#  inputs:
#    targetType: 'inline'
#    script: |
#      $version = (Select-Xml -Path ".\package.props" -XPath "/Project/PropertyGroup/VersionBase" | Select-Object -ExpandProperty Node).InnerText
#      $timestamp = git log -1 --pretty="format:%ct"
#      Write-Host "Version: $version" 
#      Write-Host "Time Stamp: $timestamp" 
#      Write-Host "##vso[task.setvariable variable=STAGE_VERSION]$($version)-$($timestamp)"

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    searchFolder: '$(system.defaultworkingdirectory)\test'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(system.defaultworkingdirectory)\src\bin\$(buildPlatform)\$(buildConfiguration)'
    ArtifactName: 'Binaries'

