# Build pipeline

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: './package.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
#  OutputPath: '$(build.artifactstagingdirectory)'
  
steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Stage package'
  inputs:
    SourceFolder: 'lib'
    Contents: '*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'CommonServiceLocator'

